/* 苔藓时间 · 数据层：基质 / 物种 / 大灭绝 / 纪元主题 */
"use strict";

const SUBSTRATES = [
  {id:"basalt",  name:"玄武岩", color:"#3a3f44", unlock:1, porosity:0.3, nutrient:0.4, note:"火山岩的余温，矿物丰富"},
  {id:"wood",    name:"腐木",   color:"#5a4632", unlock:1, porosity:0.7, nutrient:0.9, note:"腐朽即盛宴"},
  {id:"tile",    name:"瓦片",   color:"#6b4a3a", unlock:1, porosity:0.4, nutrient:0.3, note:"屋顶上被时间泡软的陶土"},
  {id:"book",    name:"旧书页", color:"#8a7d5a", unlock:2, porosity:0.6, nutrient:0.7, note:"字迹之下另有读者"},
  {id:"circuit", name:"电路板", color:"#2a4a3a", unlock:2, porosity:0.2, nutrient:0.5, note:"铜与硅的荒原"},
  {id:"glass",   name:"玻璃",   color:"#4a5a5e", unlock:3, porosity:0.05,nutrient:0.2, note:"看似一无所有的透明大陆"},
  {id:"rust",    name:"铁锈",   color:"#7a4a2a", unlock:3, porosity:0.5, nutrient:0.4, note:"氧化铁的红色沙漠"},
  {id:"bone",    name:"骨粉",   color:"#9a927e", unlock:4, porosity:0.6, nutrient:0.8, note:"磷与钙的白色原野"},
  {id:"pottery", name:"陶片",   color:"#7a5a4a", unlock:4, porosity:0.45,nutrient:0.35,note:"碎掉的容器盛着新的东西"},
  {id:"meteor",  name:"陨石",   color:"#3a3444", unlock:5, porosity:0.25,nutrient:0.6, note:"来自别处的石头，记得别处"},
];

/* 物种: need=[温度,湿度,光照,pH], tol=对应容忍±, style: moss/hypha/lichen/algae/mold/crystal/critter
   sym=共生伙伴id（互为奇观）, prey=true 表示会被菌丝绞杀 */
const SPECIES = [
  {id:"moss_common", name:"普通苔藓", style:"moss", tier:1,
   need:[20,80,40,6], tol:[10,20,30,2], subs:"any", hue:110,
   sci:"苔藓植物门，无真正的根，以假根附着。靠体表直接吸收水分，是陆地植物的古老支系，四亿年来形态几乎未变。",
   poem:"它不走，也不急。四亿年只学会一件事：把绿色铺开。"},
  {id:"moss_star", name:"星点苔藓", style:"moss", tier:1,
   need:[18,70,50,6.5], tol:[9,18,25,1.8], subs:"any", hue:95,
   sci:"孢蒴顶端具反光细胞的苔藓类群，在散射光下呈现星点状微光，可能用于吸引弹尾目小动物协助传播孢子。",
   poem:"夜空掉到地上，碎成一小片一小片，还亮着。"},
  {id:"moss_cushion", name:"垫状苔藓", style:"moss", tier:1,
   need:[15,85,30,5.5], tol:[8,15,20,1.5], subs:["basalt","tile","pottery"], hue:125,
   sci:"密集丛生的垫状生长型可在外层枯死后仍保持核心湿润，整垫如同一座自给自足的微型水库。",
   poem:"它们挤在一起取暖，外层的牺牲里层记着。"},
  {id:"lichen_glow", name:"发光地衣", style:"lichen", tier:2, sym:"fungus_nerve",
   need:[20,70,10,5.5], tol:[8,18,15,1.5], subs:["wood"], hue:80,
   sci:"真菌与藻类的共生体。部分地衣在紫外激发下发出可见荧光，其荧光物质（地衣酸衍生物）可抵御草食动物。",
   poem:"黑暗里它把自己点着，不为照亮谁，只是怕忘记自己的形状。"},
  {id:"lichen_heat", name:"耐热地衣", style:"lichen", tier:2,
   need:[40,30,90,8], tol:[15,15,20,3], subs:["basalt","tile"], hue:60,
   sci:"极端耐旱地衣，可在完全脱水状态下休眠数年，遇水数分钟内恢复光合作用。是荒漠岩面最早的定居者。",
   poem:"最干最热的地方它先住下，后来所有的绿都欠它一句谢谢。"},
  {id:"lichen_crust", name:"石壳地衣", style:"lichen", tier:2, sym:"moss_common",
   need:[25,50,60,7], tol:[12,20,25,2.5], subs:["basalt","pottery"], hue:100,
   sci:"壳状地衣以菌丝分泌草酸缓慢溶解岩石，每年可剥蚀岩面数微米——它是地质尺度上的雕刻师。",
   poem:"它吃石头，吃得很慢，慢到石头以为自己只是老了。"},
  {id:"algae_film", name:"蓝绿藻薄膜", style:"algae", tier:1,
   need:[15,90,20,7], tol:[10,10,15,2], subs:["basalt"], hue:170,
   sci:"蓝藻（蓝绿藻）是地球上最早的光合放氧生物。湿润岩面的蓝绿色黏膜实为数十亿细胞的菌落，仍保留着二十四亿年前的呼吸方式。",
   poem:"大气里的氧，最早是它一口一口吐出来的。它现在还在吐。"},
  {id:"algae_acid", name:"嗜酸红藻", style:"algae", tier:2,
   need:[30,85,35,3.5], tol:[10,12,20,1.2], subs:["glass","tile"], hue:0,
   sci:"红藻门的嗜酸种类可在 pH 3 以下的环境存活，细胞内的藻红蛋白使其呈现深红色，常见于酸性温泉与矿蚀表面。",
   poem:"酸对别人是刀，对它是酒。它在里面泡得微醺，红了脸。"},
  {id:"algae_ice", name:"冰晶藻", style:"algae", tier:2, sym:"crystal_moss",
   need:[4,60,30,6], tol:[6,20,25,2], subs:["glass","meteor"], hue:190,
   sci:"雪藻近缘种，细胞含抗冻蛋白，在冰点附近的液态水膜中仍能分裂。极地冰川的「西瓜雪」即由此类生物造成。",
   poem:"冷得越狠，它活得越认真。冰是它的温室。"},
  {id:"fungus_silicon", name:"硅基菌丝网络", style:"hypha", tier:3,
   need:[35,40,0,8], tol:[12,20,50,2], subs:["circuit"], hue:140,
   sci:"重金属耐受真菌可在电路板表面富集铜离子，菌丝沿铜箔走线生长，形成准导电网络——废弃电子垃圾上的奇异生态。",
   poem:"它顺着电流的旧路生长，像在寻找一块主板死去前最后的念头。"},
  {id:"fungus_deep", name:"深海菌丝", style:"hypha", tier:2,
   need:[5,95,10,7], tol:[5,10,10,1], subs:["wood","bone"], hue:210,
   sci:"低温寡营养真菌，菌丝极细极长，单位体积内的总长度可达数百米。在完全黑暗中以分解木质素维生。",
   poem:"它在黑里走了很久，久到把自己走成了一张地图。"},
  {id:"fungus_nerve", name:"神经菌索", style:"hypha", tier:2, sym:"lichen_glow",
   need:[22,75,15,6], tol:[8,15,20,1.5], subs:["wood"], hue:160,
   sci:"菌索是菌丝高度组织化的束状结构，可在数小时内将养分转运数厘米，其分支模式与神经网络在数学上高度同构。",
   poem:"木头里长出了别的东西的思考方式。"},
  {id:"mold_book", name:"书页霉斑", style:"mold", tier:2,
   need:[24,65,5,5], tol:[8,15,10,1.5], subs:["book"], hue:50,
   sci:"纸霉变由曲霉与青霉引起，以纤维素为食。古籍修复师称其为「狐斑」——它吃过的字，会留下茶色的轮廓。",
   poem:"它读得很慢，一页要吃好几年。读过的句子都变了颜色。"},
  {id:"mold_green", name:"陶片青霉", style:"mold", tier:1,
   need:[26,70,20,6], tol:[10,18,25,2], subs:["pottery"], hue:130,
   sci:"青霉属广泛分布于潮湿陶土表面，其分生孢子链呈扫帚状排列。1928 年，正是它的近亲点化了弗莱明的培养皿。",
   poem:"它不知道自己救过几千万人。它只知道这片陶土很软。"},
  {id:"rust_carpet", name:"锈红菌毯", style:"mold", tier:2,
   need:[32,55,25,7.5], tol:[12,20,30,2.5], subs:["rust"], hue:20,
   sci:"铁氧化细菌与真菌的混合群落，以二价铁为食，代谢产生的三价铁氧化物使菌毯与锈面几乎同色——它是锈的延续，而非入侵。",
   poem:"锈不是终点。锈也会长出活的东西。"},
  {id:"mold_bone", name:"骨粉白霉", style:"mold", tier:2,
   need:[20,60,10,7.5], tol:[8,18,15,2], subs:["bone"], hue:45,
   sci:"嗜钙真菌群落，菌丝可钻入骨盐晶体间隙，缓慢释放其中的磷。坟场的土总是格外肥，原因在此。",
   poem:"它把最后剩下的东西一点点还给土。这是世上最温柔的拆解。"},
  {id:"copper_green", name:"铜绿菌", style:"mold", tier:3,
   need:[28,50,40,8.5], tol:[10,18,30,2], subs:["circuit"], hue:175,
   sci:"能在高铜环境形成生物被膜的极端微生物群落，其分泌物加速铜面碱式碳酸铜化——铜绿其实是它们盖的屋顶。",
   poem:"铜像身上的绿衣裳，是它们一针一线缝了几十年。"},
  {id:"spike_moss", name:"耐旱卷柏苔", style:"moss", tier:2,
   need:[38,15,70,7], tol:[15,12,25,3], subs:["tile","basalt"], hue:90,
   sci:"卷柏（还魂草）可在失水 95% 后卷成枯球随风滚走，遇水展开复绿，如此反复可达数十年。严格说它不是苔藓，只是总爱混在苔藓里。",
   poem:"死给它看也没用，它只是卷起来睡一觉。醒了一百次，次次都绿。"},
  {id:"sulfur_fungus", name:"硫磺菌丝", style:"hypha", tier:3,
   need:[45,60,30,2.5], tol:[8,20,30,1], subs:["meteor"], hue:55,
   sci:"极端嗜酸嗜热古菌与真菌的伴生群落，以硫的氧化还原为能源，是深海热泉与火山口的常住者，也是地球生命起源假说的主角之一。",
   poem:"最早的生命也许就长这样：在烫手的酸汤里，觉得刚刚好。"},
  {id:"glass_algae", name:"玻璃微藻", style:"algae", tier:2,
   need:[18,88,60,6.5], tol:[9,12,25,2], subs:["glass"], hue:150,
   sci:"硅藻近缘微藻，自身分泌二氧化硅壳——它以玻璃为食，也以玻璃为屋。显微镜下壳面花纹如雪花般无一重复。",
   poem:"它住在透明的房子里，房子是吃出来的。每扇窗都不一样。"},
  {id:"crystal_moss", name:"水晶苔", style:"crystal", tier:3, sym:"algae_ice",
   need:[12,55,45,7], tol:[7,18,25,2], subs:["meteor"], hue:280,
   sci:"苔藓群落与矿物结晶的共生奇观：草酸钙晶体沿苔茎析出，形成半透明的晶簇冠层。学界对其成因仍有争论。",
   poem:"绿到极处，结成了光。"},
  {id:"tardigrade", name:"水熊虫", style:"critter", tier:3,
   need:[20,60,30,6.5], tol:[50,40,70,7], subs:"any", hue:30,
   sci:"缓步动物门，俗称水熊虫。可在隐生状态下耐受真空、辐射与 -270°C 至 150°C 的温度。它不住在任何地方，因为它哪里都住得下。",
   poem:"它只是路过。它从宇宙的任何地方路过。"},
  /* summon:true —— 不会自然涌现，只由工具或事件带入，不进图鉴 */
  {id:"beetle", name:"食腐甲虫", style:"critter", tier:1, summon:true,
   need:[20,50,50,7], tol:[50,100,100,14], subs:"any", hue:32,
   sci:"腐殖质层里的清道夫。颚部啃食衰老的苔茎与霉斑，为后来者腾出附着面——适度干扰是群落更新的齿轮。",
   poem:"它吃掉旧的部分，好让剩下的继续长。"},
  {id:"moss_invader", name:"异乡苔藓", style:"moss", tier:1, summon:true,
   need:[20,60,50,6], tol:[35,70,70,6], subs:"any", hue:135,
   sci:"随风雨迁入的外来苔藓。在没有天敌的新大陆上疯长，挤压本地种——但它的辉煌通常撑不过一个雨季。",
   poem:"它不属于这里，所以它最着急。"},
];

const SYMBIOSIS = {
  "lichen_glow+fungus_nerve": {name:"荧光共生", desc:"发光地衣的荧光物质驱退啃食者，神经菌索以养分回赠。整片视野微微发亮。"},
  "lichen_crust+moss_common": {name:"固氮绿洲", desc:"石壳地衣溶岩释出矿物，苔藓借假根固氮回哺。生长速度翻倍。"},
  "algae_ice+crystal_moss":   {name:"晶藻花园", desc:"冰晶藻的抗冻蛋白渗入苔茎，水晶苔的晶簇为藻遮光。寒带也有了春天。"},
};

const EXTINCTIONS = [
  {id:"drought", name:"干旱纪元", trait:"耐旱",
   desc:"持续数年的大旱。所有喜湿物种死亡，幸存者获得【耐旱】：湿度容忍范围永久 +50%。",
   kill:s=>s.need[1]>60},
  {id:"glacier", name:"冰川纪元", trait:"耐寒",
   desc:"冰盖推进，万物封冻。所有喜温物种死亡，幸存者获得【耐寒】：温度容忍范围永久 +8°C。",
   kill:s=>s.need[0]>15},
  {id:"volcano", name:"火山纪元", trait:"嗜酸",
   desc:"火山灰遮天蔽日，酸雨倾盆。所有中性偏好物种死亡，幸存者获得【嗜酸】：pH 容忍范围永久 +1.5。",
   kill:s=>s.need[3]>4 && s.need[3]<8},
];

const EPOCH_THEMES = [
  null,
  {name:"曙光纪元", particle:"#8fd48a", tint:null},
  {name:"繁盛纪元", particle:"#a8d46a", tint:"rgba(120,180,90,0.05)"},
  {name:"灰烬纪元", particle:"#d4a75a", tint:"rgba(180,140,70,0.06)"},
  {name:"霜雪纪元", particle:"#a8c8d4", tint:"rgba(140,180,200,0.06)"},
  {name:"异星纪元", particle:"#b48ad4", tint:"rgba(160,120,200,0.06)"},
];

const SUB_ORDER = ["basalt","wood","tile","book","circuit","glass","rust","bone","pottery","meteor"];
